### ISSUE TITLE
 learnyounode@2.7.0 need  workshopper@2.7.0

### ISSUE THREAD

**Issue by tgfjt** [workshopper/workshopper#117]
@workshopper/deploy 
That's my bad that I didn't tell you about learnyounode@2.7.0 need workshopper#master for supporting Ukrainian.

Would you publish workshopper@2.7.0?
https://github.com/workshopper/learnyounode/issues/331

**Comment by tgfjt** [comment]
we need:
* publish workshopper@2.7.0
* publish learnyounode@2.7.1

**Comment by julianduque** [comment]
@tgfjt done! 
published workshopper@2.7.0 and learnyounode@2.7.1

**Comment by tgfjt** [comment]
Thank you very much!!
