### ISSUE TITLE
workshopper-adventure

### ISSUE THREAD

**Issue by finnp** [workshopper/workshopper#122]
Hey @martinheidegger,

I'm opening this issue here, because https://github.com/martinheidegger/workshopper doesn't have an issue section.

Could you please move that repository to https://github.com/martinheidegger/workshopper-adventure and link it correctly on npm (https://www.npmjs.com/package/workshopper-adventure). And then have your working branch at the default branch (best would be to rename it to master) and activate issues there.

Right now it's super painful to track down bugs in `workshopper-adventure`, because you need to figure out where the code lives.

Best,
Finn

**Comment by martinheidegger** [comment]
I am currently working on this: https://github.com/workshopper/workshopper-adventure

**Comment by martinheidegger** [comment]
Closing this issue: btw. 4.0.4 of workshopper-adventure is released
