### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by ralphtheninja** [workshopper/workshopper#130]
I really think `workshopper` should have some kind of logo. Anyone up for submissions? :)

@substack heeeelp!

I'll pay 1 bitcoin to the winner :grinning:

**Comment by iancrowther** [comment]
@maxwellito

**Comment by RichardLitt** [comment]
I have ideas, but no current way to design stuff. Looking into getting Illustrator or Sketch so that I can design things.

**Comment by ralphtheninja** [comment]
And by `workshopper` I obviously mean the organization and not this module ;)

**Comment by iancrowther** [comment]
https://twitter.com/iancrowther/status/710975723545206788

**Comment by rynarud** [comment]
I've tried to figure out things:
![wshopper1](https://cloud.githubusercontent.com/assets/5675819/19623989/4b756eaa-98eb-11e6-9c73-041c05510bf9.png)
![wshopper2](https://cloud.githubusercontent.com/assets/5675819/19623991/5ca31d8a-98eb-11e6-8550-d211c97aa048.png)
![wshopper3](https://cloud.githubusercontent.com/assets/5675819/19623994/6eb62cba-98eb-11e6-8290-11f8eda5819f.png)
![wshopper4](https://cloud.githubusercontent.com/assets/5675819/19623995/7bcc46dc-98eb-11e6-9698-0cffef6fb303.png)

<hr>
Here I've used different colors to determine workshops. It's versatile to change.<br>
![wshopper5](https://cloud.githubusercontent.com/assets/5675819/19623998/83ab800c-98eb-11e6-9dfe-403d3df8fe7d.png)
![wshopper6](https://cloud.githubusercontent.com/assets/5675819/19624000/89b18d0c-98eb-11e6-93e8-ba36f4ff6dcc.png)
![wshopper7](https://cloud.githubusercontent.com/assets/5675819/19624001/910496b2-98eb-11e6-990d-4fd9dc3f3dd7.png)
![wshopper8](https://cloud.githubusercontent.com/assets/5675819/19624003/94f89a84-98eb-11e6-8bb3-dc229f4e1a6e.png)

<hr>

I'll be glad to get your feedback. Hope you like the general idea.

**Comment by martinheidegger** [comment]
@rynarud Moved to https://github.com/workshopper/org/issues/19

**Comment by denysdovhan** [comment]
Well, it's okay, but have you even heart of [oh-my-fish](https://github.com/oh-my-fish/oh-my-fish). They have very similar logo:

![image](https://cloud.githubusercontent.com/assets/3459374/19626102/2c2859e4-9932-11e6-909c-aca657d007b3.png)
