### ISSUE TITLE
Testing workshopper

### ISSUE THREAD

**Issue by BlackGuyCoding** [workshopper/workshopper#133]
Hi all,
I am building my first workshop and want to test it before I add a bunch of problems. I used @linclark [tutorial](http://lin-clark.com/blog/2014/07/01/authoring-nodejs-workshopper-lessons/). You can see my structure [here](https://github.com/BlackGuyCoding/JavaScript-101) as well. When I open a new terminal and mkdir, touch problem.js, enter the solution and run I get this `$ JavaScript-101 verify problem_1.js
-bash: JavaScript-101: command not found`.
I feel like I am missing a step (like something to do with creating a npm and installing the program on my machine) but there has to be a work around. Thanks is advance.

**Comment by Fauntleroy** [comment]
Could this be a problem with capitalization?

**Comment by martinheidegger** [comment]
If you do not install JavaScript-101 globally then it will not be accessible through the command line. To run the .js file locally you need to run `./JavaScript-101.js` as I also mentioned in https://github.com/BlackGuyCoding/JavaScript-101/pull/1

**Comment by BlackGuyCoding** [comment]
Fixed. Thanks @martinheidegger and @Fauntleroy
