### ISSUE TITLE
man-page formatting of output

### ISSUE THREAD

**Issue by martinheidegger** [workshopper/workshopper#82]
The current output for exercises is of non-specific width (just breaking the line when the text overflows) It would imho. be better to adopt some sort of [man-page](http://man7.org/linux/man-pages/man7/man-pages.7.html) like layouting.
- [ ] Indenting of text blocks VS. headlines
- [ ] headlines if possible without leading "#"
- [ ] Use of header sections like in man pages

What do you think?

**Comment by rvagg** [comment]
Yes, but hard. Old versions had an arbitrary width set to 70 or 80 characters in the problem statements but the arbitraryness bothered me and we also switched to using msee for markdown. 

Please feel free to work on this, we've had some success with getting changes in to msee that we want so try to do that if needed, I don't think we want to be maintaining a separate, complete formatter.

**Comment by martinheidegger** [comment]
Since there is no work done for year on `msee` and there is an open PR I think its better to just fork this `msee`
